### ISSUE TITLE
Option: disable language detection when language is not specified

### ISSUE THREAD

**Issue by DaniGuardiola** [rehypejs/rehype-highlight#11]
Add an option to disable language auto-detection entirely.

Having to add CSS classes is cumbersome on certain setups where you don't have much control over the HTML, like when you're generating it (for example, from markdown). You'd also need to add some logic to check whether a language has been specified. Most of the time if I haven't added a language it is because I just want to display some monospaced text in a nicely formatted style. Having the highlighter guess and add some seemingly random colors breaks the experience.

A simple boolean option could fix this.

**Comment by DaniGuardiola** [comment]
Might work on this myself if I find the time.

@wooorm Would like to ask for feedback before getting to work, just in case this option is not wanted for some reason. Thanks :)

**Comment by DaniGuardiola** [comment]
Omg nevermind, I didn't read the README thoroughly enough. My bad!

---

###### `options.subset`

Scope of languages to check when auto-detecting (`boolean` or `Array.<string>`,
default: all languages).
**Pass `false` to not highlight code without language classes.**

**Comment by wooorm** [comment]
nice!
