### ISSUE TITLE
Plain code when languages not in autodetect-subset, should stay unformatted but not become blank

### ISSUE THREAD

**Issue by meghprkh** [rehypejs/rehype-highlight#12]
### Subject of the issue

When using subset for language autodetection, plain code - which does not match any languages should stay unformatted.

Consider the usecase of tryng to improve time by not running autodetection for all the languages but not having to explicitly specify language for plaintext/other-language codeblocks

In my specific example I have a rpm file, which is not supported by highlightjs. I dont want code formatting for it, and would just like to keep it as plaintext without having to falsely specify plaintext as the codeblock language

### Your environment

*   **OS**: Linux
*   **Packages**: rehype-parse, rehype-stringify
*   **Env**: node-lts

### Steps to reproduce

Use `subset` and a code-block in some other language without explicit class

![image](https://user-images.githubusercontent.com/5979605/103382579-7e316800-4ae7-11eb-9623-392383032568.png)

https://codesandbox.io/s/rehype-highlight-subset-bug-o1dnx?file=/src/index.js

### Expected behavior

It should render it as unformatted text

### Actual behavior

It renders it as empty codeblock

**Comment by wooorm** [comment]
Hi there!

Automatic detection is a feature of this library. There are several ways to turn it off: you can use the [`plainText`](https://github.com/rehypejs/rehype-highlight#optionsplaintext) option: `plainText: ['plaintext']` should do what you want for the last code block.
You can also add `nohighlight` or `no-highlight` classes to code blocks you don’t want to get highlighted. Those can be used on both code blocks that you don’t want to highlight.

Are there two features enough for you?

**Comment by meghprkh** [comment]
Helo @wooorm , sorry I got caught up and was unable to reply, #13 shows the intended behaviour
