### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by rbusquet** [rehypejs/rehype-highlight#15]
### Subject of the feature

I'm using rehype-highlight with frameworks like nextjs and remix.run, and when importing the package, I get missing errors on missing type definitions when using TS.

### Problem

TS linters error with `Could not find a declaration file for module 'rehype-highlight'.`. Not a huge problem--I see other packages in the org have their types defined.

### Expected behavior

I should be able to `import highlight from "rehype-highlight"` without linter errors on TS.

### Alternatives

- @ts-ignore given that I just pass the module to a plugins list
- use inline `require` 

I'd be happy to help with a PR to add the types, following other examples!

**Comment by wooorm** [comment]
We are currently adding types gradually, and your help is appreciated. You can see some examples of types being added in
https://github.com/syntax-tree/xast-util-sitemap/pull/1, https://github.com/syntax-tree/hast-util-sanitize/pull/21, and https://github.com/syntax-tree/mdast-util-to-string/pull/5
Note that for types as a dts file, using DTSLint and/or type coverage is highly recommended.

More recently there has been a push to get types generated from JSDoc
https://github.com/wooorm/zwitch/commit/88b233db64ec7a5c791699f947ae18168febb72d  and https://github.com/wooorm/zwitch/pull/6

Either works, and a PR would be welcome!

---

Closing this issue as we don't want to keep a types tracker issue in each of the 300+ unified repos.
