### ISSUE TITLE
Update dependency lowlight version to 2.1.0

### ISSUE THREAD

**Issue by AlexanderZeilmann** [rehypejs/rehype-highlight#17]
### Subject of the feature

Update `lowlight` version to `2.1.0`.

### Problem
There are a few nice things in version of `11` of `highlight.js`.
The latest version of `lowlight` already uses version `11` of `highlight.js`, so now we only need `rehype-highlight` to use `lowlight` version `2.1.0`.

### Alternatives

I wanted to send a pull request, but the tests in the current version of `rehype-highlight` are not passing for me.

### Thank you

Thank you for all your awesome work on rehype & co :heart:

**Comment by wooorm** [comment]
Soon, this week or the next. I’m in the progress of updating everything: https://github.com/unifiedjs/unified/issues/121. Only 2 more orgs left.

**Comment by wooorm** [comment]
Done!
