### ISSUE TITLE
rehype-highlight@^4.1.0 Lacks Types

### ISSUE THREAD

**Issue by shellscape** [rehypejs/rehype-highlight#18]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-highlight@4.1.0

### Steps to reproduce

Install rehype-highlight@4.1.0 in any TypeScript project (which hasn't been configured to ignore a lack of types). 

### Expected behavior

Since v5.0.0 was a breaking change, and 4.x lacked types, I expected that a backport of types would have been made before deciding to go ESM only.

Not providing a backport to CJS is just bonkers for a tool that's so core to the ecosystem, but that aside, please consider backporting types to the 4.x version line.

### Actual behavior

Cannot find a declaration file for ...rehype-highlight

### Runtime

Node v14

### Package manager

pnpm

### OS

macOS

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
> Since v5.0.0 was a breaking change, and 4.x lacked types, I expected that a backport of types would have been made before deciding to go ESM only.

The decision to type 500+ packages was made jointly with the ESM move. Such a move through the ecosystem takes about half a year of full time work, and so it saves a lot of time to do it in one go.
Furthermore adding types has previously frequently broken existing TypeScript users, either because they are on old TS versions, or because the wrapping packages did not expect types there, or used packages in non-conforming ways, so it’s not a minor version

> Not providing a backport to CJS is just bonkers 

Please don’t insult people that give you things for free.

https://github.com/rehypejs/rehype-highlight/blob/3ecd22808c6a73a8aecc7b5fedaf758d721de208/license#L16-L22

> please consider backporting types to the 4.x version line.

I don’t have time to maintain several release lines except for security problems. I suggest that you add a `// @ts-expect-error` comment to the import, and remove it when you have the time to update your code to ESM.

**Comment by shellscape** [comment]
> Please don’t insult people that give you things for free.

Dial back the sensitivity. "Bonkers" is used as tongue in cheek in English. It would have been better to state that you didn't understand why I would have used that term, as it could be perceived as insulting, and I would have been happy to clarify. I'm a prolific open source contributor myself, and the author of https://liberamanifesto.com/, so pointing me at a license clause like that is quite humorous.

The decisions around ESM for this toolchain are on the whole disappointing, but to mark a clear oversight as wontfix without even so much as a call to action from the community is not in the spirit of open source, and with a toolchain this prolific, I'd dare say irresponsible as you are the last word.

**Comment by ChristianMurphy** [comment]
>  "Bonkers" is used as tongue in cheek in English

In both the General American Dialect and Queen's English, "Bonkers" is derogatory even in jest.

> a clear oversight 

It is not an oversight.
The new major adds TypeScript checked JSDoc https://github.com/unifiedjs/rfcs/pull/5 to generate `.d.ts` typing files.
Some packages had community contributed typings before the release, this one did not.

> without even so much as a call to action from the community is not in the spirit of open source

It is well within the spirit of open source.
As a "prolific open source contributor" you are likely well aware:
* That most projects have an active release line, and other release lines may not receive features
* That typings can also be contributed to https://github.com/DefinitelyTyped/DefinitelyTyped
* That ES Modules are well supported in Node and in Browsers, and most toolchains support ESM
* That in the event you prefer not to use ES Modules. Build tools, such as Rollup and WebPack, can be used to turn the standard ES Modules format into whichever non-standard packaging format you prefer
