### ISSUE TITLE
TS2694: Namespace '"node_modules/lowlight/lib/core"' has no exported member 'LowlightRoot'.

### ISSUE THREAD

**Issue by gsmlg** [rehypejs/rehype-highlight#19]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"rehype-highlight": "^5.0.0","lowlight": "2.4.1"

### Steps to reproduce

build with typescript

### Expected behavior

success

### Actual behavior

59): error TS2694: Namespace '"node_modules/lowlight/lib/core"' has no exported member 'LowlightRoot'.

### Runtime

Node v14

### Package manager

Other (please specify in steps to reproduce)

### OS

Linux

### Build and bundle tools

Rollup

**Comment by ChristianMurphy** [comment]
It looks like it was renamed in https://github.com/wooorm/lowlight/commit/57c4b8d4e339236b4b44455318245c03fb5ac644?diff=split#diff-826e5ed9069c92baa50ec46dde8074a6789b4c90837c5ede0e6b0438e3c34309 and may need to be updated here
