### ISSUE TITLE
rehype-highlight 导入 报错

### ISSUE THREAD

**Issue by wgh1997** [rehypejs/rehype-highlight#23]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

6.0.0

### Link to runnable example

1

### Steps to reproduce

import ReactMarkdown from 'react-markdown'
import dynamic from 'next/dynamic'
import rehypeHighlight from 'rehype-highlight'
import rehypeRaw from 'rehype-raw'
import styles from '../../styles/markdown-styles.module.css'

// const ReactMarkdown = dynamic(() => import('react-markdown').then(mod => mod.default), {
//   ssr: false,
// })
// const rehypeHighlight = dynamic(() => import('rehype-highlight').then(mod => mod.default), {
//   ssr: false,
// })

export default function Markdown({ content }) {
  return (
    // eslint-disable-next-line react/react-in-jsx-scope
    <ReactMarkdown
      className={styles.markdown}
      rehypePlugins={[rehypeRaw, rehypeHighlight]}
      // eslint-disable-next-line react/no-children-prop
      children={content}
    />
    // eslint-disable-next-line react/react-in-jsx-scope
    // <div>{content}</div>
  )
}

### Expected behavior

![Uploading image.png…]()

### Actual behavior

![Uploading image.png…]()

### Runtime

Node v17, Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack, Next.js

**Comment by ChristianMurphy** [comment]
Hey @wgh1997! 👋 
Sorry you ran into a spot of trouble.

Please spend a bit of time framing your question/bug, I don't fully understand the issue you are seeing.
https://github.com/rehypejs/.github/blob/main/support.md#asking-quality-questions
There isn't an explanation of what you are seeing, and the expected/actual behavior you posted isn't coming through.
A sandbox would go a long way to better understanding your issue as well.

From what I can gather you appear to be experiencing an import error with Next.js?
If so please make sure that your `next`, `react-markdown`, `rehype-raw`, and `rehype-highlight` are up-to-date.
These dependencies can be used together, see the following sandbox: https://stackblitz.com/edit/nextjs-h8cypk?file=pages%2F_app.js,pages%2Findex.js
which uses the following dependency version:
```json
"dependencies": {
  "highlight.js": "^11.0.0",
  "next": "^13.0.0",
  "react": "~18.0.0",
  "react-dom": "~18.0.0",
  "react-markdown": "^8.0.0",
  "rehype-highlight": "^6.0.0",
  "rehype-raw": "^6.0.0"
}
```

**Comment by ChristianMurphy** [comment]
Closing as the issue cannot be reproduced.
