### ISSUE TITLE
Option for fallback language

### ISSUE THREAD

**Issue by wong2** [rehypejs/rehype-highlight#25]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I want to specify fallback language (for example, clike) if no language is provided 

### Solution

Add an option `fallbackLanguage`

### Alternatives

No sure

**Comment by wooorm** [comment]
Sure, good idea, want to work on it?

**Comment by wooorm** [comment]
Closing this for now. I don’t particularly need this feature. I am open to someone making a prototype PR and discussing it further!
