### ISSUE TITLE
`rehype-highlight` does not register languages in production mode in Vite

### ISSUE THREAD

**Issue by hojas** [rehypejs/rehype-highlight#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

v6.0.0

### Steps to reproduce

Node.js v18

https://github.com/hojas/rehype-highlight-demo

### Expected behavior

works fine

### Actual behavior

not working

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Vite

**Comment by hojas** [comment]
`npm run dev` works fine.

`npm run build && npm run preview` got error:

```
Uncaught (in promise) Error: Unknown language: `js` is not registered
```

**Comment by wooorm** [comment]
Thanks for the repro. Looks like Vite doesn’t like [the side effects in `lowlight`](https://github.com/wooorm/lowlight/blob/be88d53cb14af192c0fd02dfebe34bddf8677ae4/package.json#L27-L30). Changing those in your `node_modules/lowlight/package.json` solves it:

```
  "sideEffects": [
    "index.js",
    "lib/all.js",
    "lib/common.js"
  ],
```

Do you want to create a PR?

**Comment by hojas** [comment]
@wooorm Thanks, let me create a PR.

**Comment by LaamGinghong** [comment]
I have encountered the same problem.
![image](https://user-images.githubusercontent.com/33472924/230761423-75216e9f-13fd-4a9d-92a0-f8bb023c8f7b.png)
 Has this problem been fixed?
