### ISSUE TITLE
Don't completely ignore plain text or unregistered languages

### ISSUE THREAD

**Issue by HerbCaudill** [rehypejs/rehype-highlight#28]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

As I mentioned in [this discussion](https://github.com/orgs/rehypejs/discussions/154#discussioncomment-7150282), I I was surprised by rehype-highlight's treatment of plain text, code blocks not tagged with a language, or tagged with an unrecognized language: 

> My mental model was that tagging code as `txt` or leaving off the language tag would fall back on a trivial "grammar" that would treat the entire block as a single token, but that would still apply the base formatting to the container.
> 
> I'd suggest that the current approach muddles together two orthogonal concerns -- what language the code block is in, and whether you want the block to be touched at all. Here's how I would think about the intent represented by various combinations:
> 
> - `language-txt no-highlight` - this is just text that I want to be rendered with `<pre>` font and whitespace; leave it completely alone
> - `language-txt` - this is text that I want rendered consistently with other code blocks, but it has no syntax so there's nothing to highlight internally
> - `language-js no-highlight` - I want to mark this as javascript code -- perhaps to get editor support, prettier formatting, or (my current use case) because that's information that a containing component needs -- but I don't want syntax highlighting or anything, leave it completely alone
> - `language-js` - I want javascript syntax highlighting

If I have a code block tagged as `txt`, or untagged, or tagged as `foo`, the block is left completely unformatted. So if I want the container to be formatted consistently with other code blocks, I have to find another way to apply the `.hljs` class, or duplicate the theme's styles in my own stylesheet. Both of these workarounds are unsatisfactory.

### Solution

When a code block is not associated with a known grammar -- whether because the language is `txt`, or no language is specified, or the specified language isn't recognized -- I'd suggest not ignoring it altogether, but still applying the `.hljs` class. This behavior could be opt-in so that it's not a breaking change. 

The `no-highlight` flag, on the other hand, would continue to have the effect is has now, which is to cause the code block to be ignored altogether. 

### Alternatives

The only workarounds I know of are the ones listed above. 

- **Applying the `.hljs` class myself**: This is possible, but depending on the original source of the markup, might be quite complex. For example, for code blocks that originate in markdown, the solution would be to write a little plugin. But this means I have to learn how remark/rehype plugins work, which adds a non-trivial layer of yak-shaving to whatever my original task was. 
-  **Duplicating the `.hljs` class's styles**: This requires me to find the theme's styles and add a rule to my style sheet applying the same styles to all `<code>` blocks. This works, but it's brittle: if I choose a different theme, or modify the theme, I have to repeat the process.

**Comment by HerbCaudill** [comment]
> Why do you want a hljs class, why not some other class?

Because I want all my code blocks to have the same background color, base text color, borders, padding etc. -- whether or not they need or support syntax highlighting. 

> to apply it for no language or unknown explicit languages seem weird?

I don't think that's weird at all. Suppose I'm writing about my new language FoobarScript and comparing it to JavaScript. Wouldn't I want my code samples to have the same background color etc.? That's what GitHub does: 

```foobar
! Hello world code sample in FoobarScript
flurgle %{ $Hello, world$ }%
```

I've confirmed that that's also what StackOverflow and GitLab do. I haven't tested anywhere else, but I'd be surprised to find a counterexample. 

There are really two separate concerns here: 

a. How I want the `<code>` block to be formatted 
b. Whether and how I want syntax coloring to be applied to various kinds of code

But since highlight.js themes take over both of those functions, I need a way to do (a) consistently regardless of (b). 

I can definitely make my own class, or just target the `<code>` element directly -- that's the workaround I'm using now. That means I have to locate the theme stylesheet and duplicate its styles. So I've taken this...

```css
pre code.hljs {
  display: block;
  overflow-x: auto;
  padding: 1em;
}
code.hljs {
  padding: 3px 5px;
}
.hljs {
  background: #474949;
  color: #d1d9e1;
}
```

...and transformed it into this:

```css
code {
  display: block;
  overflow-x: auto;
  padding: 1em;
  background: #474949;
  color: #d1d9e1;
}
```

That's not great DX, and as I noted above it's a brittle solution: if I choose a different theme, or modify the theme, I have to repeat the process. 

I suppose an alternative solution would be take the first solution I suggested -- publish a standalone plugin that does nothing but apply `.hljs` to `<code>` elements -- and document that as a solution for people who want all their code blocks to have the same background color regardless of language. But that strikes me as a jankier solution than just offering that capability as an option out of the box.

**Comment by wooorm** [comment]
I tried:

```html
<pre><code class="language-plaintext">alert(1)</code></pre>

<pre><code class="nohighlight">alert(1)</code></pre>

<pre><code>alert(1)</code></pre>

<pre><code class="language-js">alert(1)</code></pre>

<pre><code class="language-foobarscript">alert(1)</code></pre>

<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css"
/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
```

Which is turned into:

```html
<pre><code class="language-plaintext hljs">alert(1)</code></pre>

<pre><code class="nohighlight">alert(1)</code></pre>

<pre><code class="hljs language-scss"><span class="hljs-built_in">alert</span>(<span class="hljs-number">1</span>)</code></pre>

<pre><code class="language-js hljs language-javascript"><span class="hljs-title function_">alert</span>(<span class="hljs-number">1</span>)</code></pre>

<pre><code class="language-foobarscript">alert(1)</code></pre>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
<script>
  hljs.highlightAll();
</script>
```

---

> publish a standalone plugin that does nothing but apply .hljs to `<code>` elements -- and document that as a solution for people who want all their code blocks to have the same background color regardless of language. But that strikes me as a jankier solution than just offering that capability as an option out of the box.

Not all 5 line plugins need to be published. Not all plugins need to be separate packages. Not every niche feature useful to someone needs to be “out of the box” (as in: shipped to every user).

**Comment by wooorm** [comment]
You know, me asking 3 questions back doesn't mean your ideas are bad.
It's not the best customer service of course, but then again I am not customer service. You are using free stuff, and asking for me to do more things for free, and to maintain them for the next 20 years.
It requires some time, some back and forth, to figure out the best way to solve problems.

**Comment by wooorm** [comment]
Thanks for your patience and kind words!

> An unrecognized language causes the plugin to throw an error.

I don’t think that happens anymore: https://github.com/rehypejs/rehype-highlight/blob/8fbc0ebd3a0c488e7f024ef5af6983c4b49686d1/lib/index.js#L119

> It makes the plugin unusable for a site like GitHub or StackOverflow,

There was an option for that? `ignoreMissing`

> I've seen it looks like you're doing the work of 10 people.

❤️

>  my requirement ("all code blocks are formatted the same") seems like it'd be quite common, if not universal

Can’t you do that by targeting `code` and `pre code`? That’s what I always do 🤷‍♂️
