### ISSUE TITLE
How to add a copy button?

### ISSUE THREAD

**Issue by hojas** [rehypejs/rehype-highlight#30]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

How to add a copy button to copy the code?

### Solution

How to add a copy button to copy the code?

### Alternatives

How to add a copy button to copy the code?

**Comment by wooorm** [comment]
This sounds like a question. See the support guide for where to post questions.

**Comment by Vacilando** [comment]
Has this been answered anywhere?

**Comment by ChristianMurphy** [comment]
Several, web search is your friend.
The most extensive answer is https://github.com/orgs/mdx-js/discussions/1948
