### ISSUE TITLE
It looks like there is a memory leak issue

### ISSUE THREAD

**Issue by iccyuan** [rehypejs/rehype-highlight#31]
### Initial checklist

- [X] I read the [support docs](https://github.com/rehypejs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/rehypejs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/rehypejs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Arehypejs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

7.0.0

### Steps to reproduce

Render long text with typewriter effect

### Expected behavior

Memory usage is normal

### Actual behavior

Memory leak occurs after upgrading dependencies:
    "react-dom": "^18.2.0",
    "react-markdown": "^9.0.0",
    "react-router-dom": "^6.15.0",
    "rehype-highlight": "7.0.0",
    "rehype-katex": "^7.0.0",
    "remark-breaks": "^4.0.0",
    "remark-gfm": "^4.0.0",
    "remark-math": "^6.0.0",
  
 No memory leak dependencies：
    "react-dom": "^18.2.0",
    "react-markdown": "^8.0.7",
    "react-router-dom": "^6.14.1",
    "rehype-highlight": "^6.0.0",
    "rehype-katex": "^6.0.3",
    "remark-breaks": "^3.0.2",
    "remark-gfm": "^3.0.1",
    "remark-math": "^5.1.1",

**Comment by wooorm** [comment]
Closed in https://github.com/highlightjs/highlight.js/pull/4095!

**Comment by wong2** [comment]
Please upgrade `lowlight` to latest version so we can get the fix

**Comment by wooorm** [comment]
@wong2 no change is needed here; that is not how things work in the npm ecosystem. *You* need to do things. Update your things. Run `npm install`.

* https://github.com/rehypejs/rehype-highlight/blob/main/package.json#L10C1-L11C1
* https://github.com/npm/node-semver#versions

**Comment by wong2** [comment]
I'm using pnpm, I can `rehype-highlight` will still use lowlight@3.0.0 in this case?
 
- lowlight@3.30
- rehype-highlight@7.0.2
  - lowlight@3.0.0

**Comment by wooorm** [comment]
Clean your pnpm cache; pnpm chooses to never update packages normally, leaving users with buggy versions
